#!/bin/bash
# outputs the right stuff for compiling opencv tings
echo -I/usr/local/include -I/usr/local/include/opencv -I/usr/local/include/opencv2 `pkg-config --libs opencv`
#echo -I/usr/local/univ-lib/include -I/usr/local/univ-lib/include/opencv -I/usr/local/univ-lib/include/opencv2 -L/usr/local/univ-lib/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objedetect -lopencv_contrib -lopencv_legacy
